import React,{useMemo,useState} from 'react';
import ToolShell,{Panel,ToolGrid,ResultPill} from '../shared/ToolShell';
import {nearlyEqual,round} from '../shared/toolMath';
import useToolSubmission from '../shared/useToolSubmission';

export default function StepAlgebra2({questionData={},onAction}){
 const original=questionData.equation||{a:3,b:6,c:21};
 const [state,setState]=useState({...original}); const [operation,setOperation]=useState('subtract'); const [operand,setOperand]=useState(''); const [history,setHistory]=useState([]); const {feedback,submit}=useToolSubmission(onAction);
 const solution=useMemo(()=> (Number(original.c)-Number(original.b))/Number(original.a),[original]);
 const apply=()=>{const n=Number(operand);if(!Number.isFinite(n)||n===0&&['multiply','divide'].includes(operation))return;let next={...state};if(operation==='add'){next.b+=n;next.c+=n;}if(operation==='subtract'){next.b-=n;next.c-=n;}if(operation==='multiply'){next.a*=n;next.b*=n;next.c*=n;}if(operation==='divide'){next.a/=n;next.b/=n;next.c/=n;}setHistory(h=>[...h,{before:state,operation,operand:n,after:next}]);setState(next);setOperand('');};
 const solved=nearlyEqual(state.a,1,1e-9)&&nearlyEqual(state.b,0,1e-9);
 const check=()=>submit({isCorrect:solved&&nearlyEqual(state.c,solution,0.01),score:solved?1:0},{history,state});
 const fmt=(s)=>`${round(s.a,3)}x ${Number(s.b)>=0?'+':'−'} ${Math.abs(round(s.b,3))} = ${round(s.c,3)}`;
 return <ToolShell title="Step Algebra 2.0" subtitle="Apply symbolic operations to both sides with a compact, auditable step history." badge="Core upgrade"><ToolGrid min={330}><Panel title="Equation workspace"><div style={{fontSize:26,fontWeight:800,textAlign:'center',padding:18,background:'#fff',border:'1px solid #d9e2f1',borderRadius:12}}>{fmt(state)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr auto',gap:8,marginTop:14}}><select value={operation} onChange={e=>setOperation(e.target.value)} style={{padding:10}}><option value="add">Add</option><option value="subtract">Subtract</option><option value="multiply">Multiply</option><option value="divide">Divide</option></select><input type="number" value={operand} onChange={e=>setOperand(e.target.value)} placeholder="operand" style={{padding:10}}/><button type="button" onClick={apply} style={{padding:'10px 14px',border:0,borderRadius:8,background:'#174ea6',color:'#fff',fontWeight:800}}>Apply</button></div><button type="button" onClick={check} style={{marginTop:12,padding:'10px 16px',border:0,borderRadius:8,background:'#1a73e8',color:'#fff',fontWeight:800}}>Check solution</button>{feedback?<div style={{marginTop:12}}><ResultPill ok={feedback.isCorrect}>{feedback.isCorrect?`Solved: x = ${round(solution,3)}`:'Keep equivalent operations balanced on both sides.'}</ResultPill></div>:null}</Panel><Panel title="Step history">{history.length?history.map((step,i)=><div key={i} style={{padding:'9px 0',borderBottom:'1px solid #edf1f6'}}><strong>{i+1}.</strong> {step.operation} {step.operand}<div style={{color:'#5f6b7a',fontSize:13}}>{fmt(step.before)} → {fmt(step.after)}</div></div>):<p style={{color:'#5f6b7a'}}>Your operations will appear here. This replaces the heavier button-grid workflow and is ready to use MathMasterInput for symbolic operands.</p>}</Panel></ToolGrid></ToolShell>;
}
