import React from 'react';

const Card = ({ label, value, note }) => <article style={{ border: '1px solid #dadce0', borderRadius: 12, padding: 17, background: '#fff' }}><div style={{ color: '#5f6368', fontSize: 12, fontWeight: 800, textTransform: 'uppercase' }}>{label}</div><div style={{ fontSize: 30, fontWeight: 900, margin: '5px 0', color: '#174ea6' }}>{value}</div>{note && <div style={{ color: '#5f6368', fontSize: 12 }}>{note}</div>}</article>;

export const DistrictAnalyticsView = ({ analytics, title = 'College & mastery readiness' }) => {
  if (!analytics) return null;
  const readiness = analytics.collegeReadiness;
  return <section><h2>{title}</h2><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(170px,1fr))', gap: 12 }}><Card label="Students" value={analytics.totalStudents} /><Card label="SAT Math on track" value={readiness.digitalSAT.readyRate == null ? '—' : `${readiness.digitalSAT.readyRate}%`} note={`n=${readiness.digitalSAT.sampleSize} evidence-qualified`} /><Card label="ACT Math on track" value={readiness.act.readyRate == null ? '—' : `${readiness.act.readyRate}%`} note={`n=${readiness.act.sampleSize} evidence-qualified`} /><Card label="TSIA2 CRC on track" value={readiness.tsia2.readyRate == null ? '—' : `${readiness.tsia2.readyRate}%`} note={`n=${readiness.tsia2.sampleSize}; Diagnostic Level 6 is an alternate official pathway`} /><Card label="Students with supports" value={`${analytics.specialPrograms.supportedPercentage}%`} note={`${analytics.specialPrograms.supportedUniqueCount} unique students`} /></div><p style={{ color: '#5f6368', fontSize: 12, lineHeight: 1.5 }}>{readiness.note}</p><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 540, borderCollapse: 'collapse' }}><thead><tr><th style={{ textAlign: 'left', padding: 8 }}>Algebra I strand</th><th style={{ textAlign: 'left', padding: 8 }}>Estimated mastery</th><th style={{ textAlign: 'left', padding: 8 }}>Evidence points</th></tr></thead><tbody>{Object.entries(analytics.strandAverages).map(([id, strand]) => <tr key={id}><td style={{ padding: 8, borderTop: '1px solid #eee' }}>{strand.title}</td><td style={{ padding: 8, borderTop: '1px solid #eee' }}>{strand.estimate == null ? 'Not enough evidence' : `${strand.estimate}%`}</td><td style={{ padding: 8, borderTop: '1px solid #eee' }}>{strand.evidenceCount}</td></tr>)}</tbody></table></div></section>;
};

export default DistrictAnalyticsView;
