/*
 * THE DETERMINISTIC-HONORS COVERAGE REPORT, AS A DOCUMENT.
 *
 * Renders buildHonorsCoverageReport() (src/platform/rigor/honorsRecipeCoverage.js)
 * as the markdown and JSON committed under docs/honors/. Both files are
 * generated, never hand-edited, so neither can claim a coverage the code does
 * not have: tests/platform/honorsRecipeCoverage.test.mjs fails when they are
 * stale. Regenerate with:
 *
 *   node scripts/report-honors-coverage.mjs --write
 *
 * Pure: report in, text out.
 */

export const COVERAGE_MARKDOWN_PATH = 'docs/honors/DETERMINISTIC_HONORS_COVERAGE.md';
export const COVERAGE_JSON_PATH = 'docs/honors/deterministic-honors-coverage.json';

const STATUSES = Object.freeze(['READY', 'CAPABLE', 'BLOCKED', 'NOT APPROPRIATE']);

const cell = (value) => String(value ?? '')
  .replace(/\s+/g, ' ')
  .replace(/\|/g, '\\|')
  .trim();

const familyRow = (row) => {
  if (row.status === 'READY') {
    const recipes = row.recipes.map((recipe) => `\`${recipe.id}\` v${recipe.version} — ${recipe.title}`).join('<br>');
    return `| \`${row.familyId}\` | **READY** | ${cell(recipes)} | — |`;
  }
  return `| \`${row.familyId}\` | ${row.status} | ${cell(row.reason)} | ${cell(row.missingCapability || '—')} |`;
};

const conceptRow = (entry) => {
  const teks = entry.teks.length ? entry.teks.join(', ') : cell(entry.note);
  return `| ${cell(entry.concept)} | ${cell(teks)} | ${cell(entry.existingTools.map((tool) => `\`${tool}\``).join(', '))} | ${cell(entry.missingCapability)} |`;
};

const recipeSection = (recipe, anchors) => [
  `### \`${recipe.id}\` v${recipe.version}`,
  '',
  `${recipe.title}.`,
  '',
  `- **Anchor family:** ${anchors.map((anchor) => `\`${anchor.familyId}\` (${anchor.courseLabel})`).join(', ')}`,
  `- **Builds and grades it:** ${recipe.target}`,
  `- **Rigor:** lesson DOK ${recipe.baseline.dok}, band ${recipe.baseline.difficultyBand} → Honors DOK ${recipe.honors.dok}, band ${recipe.honors.difficultyBand}`,
  `- **Delivery:** ${recipe.delivery.perStudentVersions ? 'a generated version per student' : 'one shared version'} · ${recipe.delivery.serverGraded ? 'marked by the server' : 'not server-marked'} · ${recipe.delivery.recoveryReady ? 'Recovery-ready' : 'not Recovery-ready'} · self-graded: ${recipe.selfGraded ? 'yes' : 'no'}`,
  `- **Stories (swap alternatives):** ${recipe.stories.map((story) => `\`${story}\``).join(', ')}`,
  '- **How it is harder:**',
  ...recipe.increases.map((increase) => `  - ${increase}`),
  '',
];

export const renderHonorsCoverageMarkdown = (report) => {
  const courses = Object.values(report.courses);
  const lines = [
    '# Deterministic (no-AI) Honors coverage',
    '',
    '> Generated by `node scripts/report-honors-coverage.mjs --write` from',
    '> `src/platform/rigor/honorsRecipeCoverage.js`. Do not edit by hand:',
    '> `tests/platform/honorsRecipeCoverage.test.mjs` fails when this file is stale.',
    '',
    '"Add built-in Honors extension (no AI)" builds an extension only from a **vetted recipe**:',
    'a self-graded task on an existing rich tool, generated per student and marked by the',
    'server. Where no recipe fits the assignment\'s concept and course, MathMaster adds',
    'nothing and says why. This report is what the teacher can rely on, family by family.',
    '',
    '| Status | Meaning |',
    '| --- | --- |',
    '| **READY** | A vetted recipe exists for this family in this course (computed from the recipe registry). |',
    '| CAPABLE | The family and its tool could carry a genuine Honors task today; the recipe is not written yet. |',
    '| BLOCKED | They cannot. The last column names exactly what would unblock it. |',
    '| NOT APPROPRIATE | Built-in Honors for this family in this course would mislead (it is the other course\'s content). |',
    '',
    '## Summary',
    '',
    `| Course | Registered families | ${STATUSES.join(' | ')} | Concepts with no registered family |`,
    `| --- | --- | ${STATUSES.map(() => '---').join(' | ')} | --- |`,
    ...courses.map((course) => `| ${course.label} | ${course.families.length} | ${STATUSES.map((status) => course.familySummary[status]).join(' | ')} | ${course.concepts.length} (all BLOCKED) |`),
    '',
  ];
  courses.forEach((course) => {
    lines.push(
      `## ${course.label}`,
      '',
      '### Registered Question Families',
      '',
      '| Family | Status | Recipe, or why not | What would unblock it |',
      '| --- | --- | --- | --- |',
      ...course.families.map(familyRow),
      '',
      '### Concepts with no registered Question Family',
      '',
      'The rich tool and its server grader already exist; only a generator (a registered Question Family) is missing.',
      '',
      '| Concept | TEKS | Existing tool (mode), server-graded | Missing |',
      '| --- | --- | --- | --- |',
      ...course.concepts.map(conceptRow),
      '',
    );
  });
  const recipes = new Map();
  courses.forEach((course) => course.families.forEach((row) => row.recipes.forEach((recipe) => {
    if (!recipes.has(recipe.id)) recipes.set(recipe.id, { recipe, anchors: [] });
    recipes.get(recipe.id).anchors.push({ familyId: row.familyId, courseLabel: course.label });
  })));
  lines.push('## Vetted recipes', '');
  [...recipes.values()].forEach(({ recipe, anchors }) => lines.push(...recipeSection(recipe, anchors)));
  return `${lines.join('\n').trimEnd()}\n`;
};

export const renderHonorsCoverageJson = (report) => `${JSON.stringify(report, null, 2)}\n`;
