/*
 * JOB K — THE fractions FAMILY'S WORKED SOLUTION OF THE QUESTION ITSELF.
 *
 * workedSolution(question) is what the closed-question review panel shows
 * when a fraction item has no authored solution steps (closedQuestionReview.js):
 * the question's OWN operands worked by the family's sibling workers (common
 * denominator, straight across, reciprocal, greatest common factor). This file
 * draws every shape the family can work —
 *   - sum         drills generated by the real problemGenerator (default and
 *                 authored denominators, many seats) and V5-authored sums,
 *                 negatives included;
 *   - arithmetic  V5-authored + − × ÷ in symbols and words, a whole number,
 *                 a negative divisor, a zero result, a whole-number result;
 *   - simplify    the browser fixture's family / template / authored slots,
 *                 drawn for real seats, and V5 "Simplify 6/8." / "Simplify."
 *                 over \frac{6}{8};
 *   - multiAnswer one free-response field, V5-compiled;
 * and the shapes it must refuse (`form` items, a key the work disagrees with).
 *
 * Every step is read back from its TEXT and recomputed with mathjs in exact
 * Fraction arithmetic, never with the family's helpers:
 *   - every "a = b = c" written in math holds, and is worth an operand or the
 *     answer; every least common multiple / greatest common factor / "lowest
 *     terms" claim is true;
 *   - each step starts from fractions an earlier step (or the problem) wrote:
 *     the chain is unbroken;
 *   - the last step is "So <the problem> = <value>" with <value> the key;
 *   - the shared graders (gradeResponseField, and the type's own
 *     gradeFractionResponse / gradeMultiAnswerResponse) mark the stated answer
 *     right;
 *   - the text has no "+ -3", "--", "-0", NaN, null or undefined.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { all, create } from 'mathjs';

import * as fractions from '../../src/platform/supports/families/fractions.js';
import { familyFor } from '../../src/platform/supports/families/index.js';
import { buildClosedQuestionReview } from '../../src/platform/supports/review/closedQuestionReview.js';
import { gradeResponseField } from '../../src/grading/fieldGrader.js';
import { gradeFractionResponse, gradeMultiAnswerResponse } from '../../functions/shared/ordinaryResponseGrading.mjs';
import { generateQuestion } from '../../src/problemGenerator.js';
import { parseAssignmentBlueprintText, validateAssignmentQuestions } from '../../src/assignmentBlueprint.js';
import { questionFor, generationKeyFor, familyContextFor } from '../browser/fractionTemplateGradingFixture.mjs';
import { executableSource } from './helpers/sourceContract.mjs';

const ROOT = new URL('../../', import.meta.url);

/* ------------------------------------------------------------ the independent oracle */

const math = create(all, { number: 'Fraction' });
const F = (value) => math.fraction(value);

/** A LaTeX number expression as mathjs reads it: \frac, \times, \div, parentheses. */
const toMath = (latex) => {
  let source = String(latex).trim();
  for (let pass = 0; pass < 4; pass += 1) source = source.replace(/\\frac\{([^{}]*)\}\{([^{}]*)\}/g, '(($1)/($2))');
  assert.doesNotMatch(source, /\\(?!times|div)[a-z]/i, `a readable number expression: ${latex}`);
  return source.replace(/\\times/g, '*').replace(/\\div/g, '/');
};
const valueOf = (latex) => F(math.evaluate(toMath(latex)));
const mathSegments = (line) => [...String(line).matchAll(/\$([^$]+)\$/g)].map((match) => match[1]);
const fracTokens = (latex) => [...String(latex).matchAll(/-?\\frac\{\d+\}\{\d+\}/g)].map((match) => match[0]);
const gcd = (a, b) => Number(math.gcd(math.bignumber(Math.abs(a)), math.bignumber(Math.abs(b))));
const lcm = (a, b) => (a / gcd(a, b)) * b;

/** The key the question holds, read without the family. */
const keyOf = (question) => {
  if (question.type === 'multiAnswer') return F(question.answerFields[0].answer);
  if (Number.isInteger(question.ansNum) && Number.isInteger(question.ansDen)) return F(question.ansNum).div(question.ansDen);
  if (Number.isInteger(question.n1)) return F(question.n1).div(question.d1).add(F(question.n2).div(question.d2));
  return F(String(question.answer));
};

const SLOPPY = /NaN|undefined|\bnull\b|\[object|\+\s*-|--|(?<![\d.])-0(?![\d./])/;

/**
 * Verify one worked solution against the problem the TEST states:
 * `problem` is the LaTeX of the operation (or the fraction to simplify),
 * `operands` the values the problem is made of.
 */
const verifyWorked = (label, question, { problem, operands, kind }) => {
  const worked = fractions.workedSolution(question);
  assert.ok(worked, `${label}: a worked solution`);
  const { headline, steps, answerSummary } = worked;
  const answer = valueOf(problem);
  assert.ok(answer.equals(keyOf(question)), `precondition ${label}: ${problem} is worth the key`);
  assert.ok(steps.length >= 3, `${label}: worked in steps`);
  [headline, ...steps, answerSummary].forEach((line) => assert.doesNotMatch(line, SLOPPY, `${label}: "${line}"`));
  assert.ok(mathSegments(headline).some((segment) => valueOf(segment).equals(answer)), `${label}: the headline names this problem`);

  const seen = new Set([...fracTokens(headline), ...fracTokens(problem)]);
  operands.forEach((value) => seen.add(String(value)));
  steps.forEach((step, index) => {
    for (const segment of mathSegments(step)) {
      if (!segment.includes('=')) continue;
      const sides = segment.split('=').map((side) => side.trim());
      const values = sides.map(valueOf);
      values.forEach((value, at) => assert.ok(value.equals(values[0]), `${label}: "${segment}" holds (${sides[at]})`));
      // Worth an operand (a rewrite) or the answer (everything else).
      assert.ok([answer, ...operands].some((value) => value.equals(values[0])), `${label}: "${segment}" is worth an operand or the answer`);
      // Chained: the fractions it starts from were written before.
      if (index > 0) fracTokens(sides[0]).forEach((token) => assert.ok(seen.has(token) || seen.has(token.replace(/^-/, '')), `${label}: "${step}" starts from ${token}, which no earlier step wrote`));
    }
    const lcmClaim = /least common multiple of \$(\d+)\$ and \$(\d+)\$ is \$(\d+)\$/.exec(step);
    if (lcmClaim) assert.equal(Number(lcmClaim[3]), lcm(Number(lcmClaim[1]), Number(lcmClaim[2])), `${label}: ${step}`);
    const gcfClaim = /greatest common factor of the numerator \$(-?\d+)\$ and the denominator \$(\d+)\$: it is \$(\d+)\$/.exec(step);
    if (gcfClaim) assert.equal(Number(gcfClaim[3]), gcd(Number(gcfClaim[1]), Number(gcfClaim[2])), `${label}: ${step}`);
    const divideBy = /^Simplify: divide the numerator and denominator by \$(\d+)\$: \$(-?)\\frac\{(\d+)\}\{(\d+)\}/.exec(step);
    if (divideBy) assert.equal(Number(divideBy[1]), gcd(Number(divideBy[3]), Number(divideBy[4])), `${label}: divides by the greatest common factor: ${step}`);
    const lowest = /^\$(-?\\frac\{(\d+)\}\{(\d+)\})\$ is already in lowest terms|^Check: \$(\d+)\$ and \$(\d+)\$ share no factor/.exec(step);
    if (lowest) {
      const [p, q] = lowest[2] ? [lowest[2], lowest[3]] : [lowest[4], lowest[5]];
      assert.equal(gcd(Number(p), Number(q)), 1, `${label}: ${step}`);
    }
    for (const segment of mathSegments(step)) fracTokens(segment).forEach((token) => seen.add(token));
    mathSegments(step).forEach((segment) => segment.split('=').forEach((side) => seen.add(side.trim())));
  });

  // The last step is "So <problem> = <answer>", with the answer the key.
  const last = steps.at(-1);
  const final = /^So \$(.+) = ([^=$]+)\$(?:, written \$([^$]+)\$)?\.$/.exec(last);
  assert.ok(final, `${label}: the last step states the answer: ${last}`);
  assert.ok(valueOf(final[1]).equals(answer), `${label}: the last step restates the problem`);
  assert.ok(valueOf(final[2]).equals(keyOf(question)), `${label}: the last step ends on the key`);
  if (kind === 'simplify' || question.type !== 'fraction' || !final[3]) {
    const [, top, bottom] = /\\frac\{(\d+)\}\{(\d+)\}$/.exec(final[2]) || [null, String(Math.abs(Number(final[2]))), '1'];
    assert.equal(gcd(Number(top), Number(bottom)), 1, `${label}: the answer is in lowest terms`);
  }

  // The stated answer, graded by the shared graders.
  const summary = /^The answer is \$([^$]+)\$\.$/.exec(answerSummary);
  assert.ok(summary, `${label}: the summary states the answer: ${answerSummary}`);
  const stated = summary[1];
  assert.equal(stated, final[3] || final[2], `${label}: the summary and the last step agree`);
  const statedFraction = /\\frac\{(\d+)\}\{(\d+)\}$|(\d+)\/(\d+)$/.exec(stated);
  if (statedFraction) {
    const [p, q] = statedFraction[1] ? [statedFraction[1], statedFraction[2]] : [statedFraction[3], statedFraction[4]];
    assert.equal(gcd(Number(p), Number(q)), 1, `${label}: the stated answer ${stated} is in lowest terms`);
  }
  const typed = stated.replace(/^(-?)\\frac\{(\d+)\}\{(\d+)\}$/, '$1$2/$3');
  if (question.type === 'multiAnswer') {
    const [field] = question.answerFields;
    assert.equal(gradeMultiAnswerResponse(question, { [field.id]: typed }).isCorrect, true, `${label}: the multiAnswer grader accepts ${typed}`);
    assert.equal(gradeResponseField({ expected: field.answer, accepted: field.acceptedAnswers }, typed).isCorrect, true, `${label}: gradeResponseField accepts ${typed}`);
  } else {
    assert.equal(gradeFractionResponse(question, typed).isCorrect, true, `${label}: the fraction grader accepts ${typed}`);
    assert.equal(gradeFractionResponse(question, stated).isCorrect, true, `${label}: the fraction grader accepts ${stated}`);
    const expected = Number.isInteger(question.n1) ? keyOf(question).toFraction() : String(question.answer);
    assert.equal(gradeResponseField({ expected }, typed).isCorrect, true, `${label}: gradeResponseField accepts ${typed}`);
  }
  return worked;
};

/* ------------------------------------------------------------ the real items */

const fr = (value) => {
  const f = F(value);
  const n = Number(f.s) * Number(f.n);
  return Number(f.d) === 1 ? String(n) : `${n < 0 ? '-' : ''}\\frac{${Math.abs(n)}}{${Number(f.d)}}`;
};
const ITEMS = [];
const add = (label, question, problem, operands, kind) => ITEMS.push({ label, question, problem, operands: operands.map(F), kind });

const compileV5 = (questions) => {
  const parsed = parseAssignmentBlueprintText(JSON.stringify({
    schemaVersion: 5,
    assignment: { title: 'Fraction worked solutions', courseId: 'algebra1' },
    sections: [{ role: 'practice', title: 'Practice', questions }],
  }));
  validateAssignmentQuestions(parsed.questions);
  return parsed.questions;
};

// Drills, generated as the browser generates them, over many seats.
for (const blueprint of [{ type: 'fraction', prompt: 'Add the fractions.' }, { type: 'fraction', prompt: 'Add the fractions.', generator: { denominators: [2, 3, 4] } }, { type: 'fraction', prompt: 'Add.', generator: { denominators: [6, 8, 9, 12] } }]) {
  for (let seat = 0; seat < 40; seat += 1) {
    const question = generateQuestion(blueprint, `k-steps|seat-${seat}|${seat % 5}|variant:0`);
    const { n1, d1, n2, d2 } = question;
    add(`drill ${n1}/${d1} + ${n2}/${d2}`, question, `${fr(`${n1}/${d1}`)} + ${fr(`${n2}/${d2}`)}`, [`${n1}/${d1}`, `${n2}/${d2}`], 'sum');
  }
}

// Authored sums: negatives, equal denominators, a whole-number and a zero result.
const SUMS = [[1, 2, 1, 3], [3, 8, 5, 8], [1, 4, 3, 4], [-1, 2, 1, 3], [-3, 4, 1, 4], [5, 6, 1, 4], [2, 3, 3, 4], [7, 10, 2, 5], [-1, 4, 1, 4], [-5, 6, -1, 6], [3, 10, -7, 15]];
compileV5(SUMS.map(([n1, d1, n2, d2]) => ({ standard: 'A.3C', prompt: 'Add.', studentActions: ['fractionAnswer'], n1, d1, n2, d2 })))
  .forEach((authored, index) => {
    const [n1, d1, n2, d2] = SUMS[index];
    const question = generateQuestion(authored, `k-steps-sum|${index}|variant:0`);
    assert.deepEqual([question.n1, question.d1, question.n2, question.d2], SUMS[index], 'the author\'s operands are kept');
    add(`authored sum ${n1}/${d1} + ${n2}/${d2}`, question, `${fr(`${n1}/${d1}`)} + ${n2 < 0 ? `(${fr(`${n2}/${d2}`)})` : fr(`${n2}/${d2}`)}`, [`${n1}/${d1}`, `${n2}/${d2}`], 'sum');
  });

// Simplify: the browser fixture's three slots, drawn for real seats.
for (const kind of ['family', 'template', 'authored']) {
  for (let seat = 0; seat < (kind === 'authored' ? 2 : 12); seat += 1) {
    const question = generateQuestion(questionFor(kind), generationKeyFor(seat), null, null, familyContextFor(kind));
    const [, n, d] = /^Simplify (\d+)\/(\d+)\.$/.exec(question.prompt);
    add(`simplify ${kind} seat ${seat}: ${question.prompt}`, question, `\\frac{${n}}{${d}}`, [`${n}/${d}`], 'simplify');
  }
}
{
  const [plain, line, already] = compileV5([
    { standard: 'A.3C', prompt: 'Simplify 6/8.', studentActions: ['fractionAnswer'], answer: '3/4' },
    { standard: 'A.3C', prompt: 'Simplify.', studentActions: ['fractionAnswer'], answer: '3/4', expressionLatex: '\\frac{6}{8} =' },
    { standard: 'A.3C', prompt: 'Simplify 18/6.', studentActions: ['fractionAnswer'], answer: '3' },
  ]).map((question, index) => generateQuestion(question, `k-steps-simplify|${index}`));
  add('V5 Simplify 6/8.', plain, '\\frac{6}{8}', ['6/8'], 'simplify');
  add('V5 Simplify. over \\frac{6}{8} =', line, '\\frac{6}{8}', ['6/8'], 'simplify');
  add('V5 Simplify 18/6. (a whole number)', already, '\\frac{18}{6}', ['18/6'], 'simplify');
}

// Authored arithmetic, compiled by V5. The test states each problem itself.
const ARITHMETIC = [
  { prompt: 'Add 3/8 + 3/8.', answer: '6/8', problem: '\\frac{3}{8} + \\frac{3}{8}', operands: ['3/8', '3/8'] },
  { prompt: 'Subtract: $\\frac{5}{6} - \\frac{1}{4}$', answer: '7/12', problem: '\\frac{5}{6} - \\frac{1}{4}', operands: ['5/6', '1/4'] },
  { prompt: 'Subtract 1/4 from 5/6.', answer: '7/12', problem: '\\frac{5}{6} - \\frac{1}{4}', operands: ['5/6', '1/4'] },
  { prompt: 'Multiply $\\frac{2}{3} \\times \\frac{3}{4}$.', answer: '1/2', problem: '\\frac{2}{3} \\times \\frac{3}{4}', operands: ['2/3', '3/4'] },
  { prompt: 'Find the product of $\\frac{2}{3}$ and $\\frac{3}{5}$.', answer: '2/5', problem: '\\frac{2}{3} \\times \\frac{3}{5}', operands: ['2/3', '3/5'] },
  { prompt: 'Divide $\\frac{1}{2} \\div \\frac{1}{4}$.', answer: '2', problem: '\\frac{1}{2} \\div \\frac{1}{4}', operands: ['1/2', '1/4'] },
  { prompt: 'Divide: 3/4 ÷ 3/8', answer: '2', problem: '\\frac{3}{4} \\div \\frac{3}{8}', operands: ['3/4', '3/8'] },
  { prompt: 'Find the sum.', expressionLatex: '\\frac{2}{5} + \\frac{1}{10} =', answer: '1/2', problem: '\\frac{2}{5} + \\frac{1}{10}', operands: ['2/5', '1/10'] },
  { prompt: 'Subtract: $\\frac{1}{4} - \\frac{3}{4}$', answer: '-1/2', problem: '\\frac{1}{4} - \\frac{3}{4}', operands: ['1/4', '3/4'] },
  { prompt: 'Add $-1 + \\frac{1}{2}$.', answer: '-1/2', problem: '-1 + \\frac{1}{2}', operands: ['-1', '1/2'] },
  { prompt: 'Multiply $2 \\times \\frac{3}{4}$.', answer: '3/2', problem: '2 \\times \\frac{3}{4}', operands: ['2', '3/4'] },
  { prompt: 'Divide $3 \\div \\frac{1}{2}$.', answer: '6', problem: '3 \\div \\frac{1}{2}', operands: ['3', '1/2'] },
  { prompt: 'Compute 3/4 ÷ -3/8.', answer: '-2', problem: '\\frac{3}{4} \\div (-\\frac{3}{8})', operands: ['3/4', '-3/8'] },
  { prompt: 'Compute 2/3 × -9/4.', answer: '-3/2', problem: '\\frac{2}{3} \\times (-\\frac{9}{4})', operands: ['2/3', '-9/4'] },
  { prompt: 'Compute -5/6 + -1/4.', answer: '-13/12', problem: '-\\frac{5}{6} + (-\\frac{1}{4})', operands: ['-5/6', '-1/4'] },
  { prompt: 'Subtract: 3/5 - 3/5', answer: '0', problem: '\\frac{3}{5} - \\frac{3}{5}', operands: ['3/5', '3/5'] },
  { prompt: 'Add 1/4 + 3/4.', answer: '1', problem: '\\frac{1}{4} + \\frac{3}{4}', operands: ['1/4', '3/4'] },
];
compileV5(ARITHMETIC.map(({ prompt, answer, expressionLatex }) => ({ standard: 'A.3C', prompt, studentActions: ['fractionAnswer'], answer, ...(expressionLatex ? { expressionLatex } : {}) })))
  .forEach((authored, index) => {
    const { prompt, problem, operands } = ARITHMETIC[index];
    add(`authored ${prompt}`, generateQuestion(authored, `k-steps-arith|${index}`), problem, operands, 'arithmetic');
  });

// multiAnswer: one free-response field whose key is the result shown.
const MULTI = [
  { prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', label: 'Sum', answer: '5/6', problem: '\\frac{1}{2} + \\frac{1}{3}', operands: ['1/2', '1/3'] },
  { prompt: 'Find the difference.', label: '$\\frac{3}{4} - \\frac{1}{6} =$', answer: '7/12', problem: '\\frac{3}{4} - \\frac{1}{6}', operands: ['3/4', '1/6'] },
  { prompt: 'Multiply: $\\frac{4}{5} \\times \\frac{5}{6}$', label: 'Product', answer: '2/3', problem: '\\frac{4}{5} \\times \\frac{5}{6}', operands: ['4/5', '5/6'] },
  { prompt: 'Divide $\\frac{2}{3} \\div \\frac{4}{9}$.', label: 'Quotient', answer: '3/2', problem: '\\frac{2}{3} \\div \\frac{4}{9}', operands: ['2/3', '4/9'] },
  { prompt: 'Simplify $\\frac{12}{16}$.', label: 'Simplest form', answer: '3/4', problem: '\\frac{12}{16}', operands: ['12/16'], kind: 'simplify' },
];
compileV5(MULTI.map(({ prompt, label, answer }) => ({ standard: 'A.3C', prompt, studentActions: ['multipleResponses'], responses: [{ id: 'result', label, answer }] })))
  .forEach((question, index) => {
    const { prompt, problem, operands, kind = 'arithmetic' } = MULTI[index];
    assert.equal(question.type, 'multiAnswer');
    add(`multiAnswer ${prompt}`, question, problem, operands, kind);
  });

/* ------------------------------------------------------------ tests */

test('the corpus has every shape several times over, each owned by the fractions family', () => {
  const count = (kind) => ITEMS.filter((item) => item.kind === kind).length;
  assert.ok(count('sum') >= 120, `sums: ${count('sum')}`);
  assert.ok(count('simplify') >= 25, `simplify: ${count('simplify')}`);
  assert.ok(count('arithmetic') >= 20, `arithmetic: ${count('arithmetic')}`);
  for (const symbol of ['+', '-', '\\times', '\\div']) {
    assert.ok(ITEMS.filter((item) => item.kind === 'arithmetic' && item.problem.includes(symbol)).length >= 3, `arithmetic ${symbol}`);
  }
  assert.ok(ITEMS.filter((item) => item.question.type === 'multiAnswer').length >= 5, 'multiAnswer items');
  ITEMS.forEach(({ label, question }) => assert.equal(familyFor(question), fractions, `${label}: owned by fractions`));
});

test('every worked step is true, follows from the one before, and ends on the key the grader accepts', () => {
  for (const { label, question, problem, operands, kind } of ITEMS) verifyWorked(label, question, { problem, operands, kind });
});

test('edges read the way a student works them: signs in parentheses, a whole number written over 1, the reciprocal keeps its sign', () => {
  const ws = (prompt, answer) => fractions.workedSolution({ type: 'fraction', prompt, answer });
  const negative = ws('Compute 3/4 ÷ -3/8.', '-2');
  assert.ok(negative.steps.some((step) => step.includes('its reciprocal, $-\\frac{8}{3}$')), negative.steps.join('\n'));
  assert.ok(negative.steps.some((step) => step.includes('\\times (-\\frac{8}{3})') && step.includes('\\times (-8)')), negative.steps.join('\n'));
  const whole = ws('Add $-1 + \\frac{1}{2}$.', '-1/2');
  assert.equal(whole.steps[0], 'Write the whole number $-1$ as a fraction: $-1 = -\\frac{1}{1}$.');
  const minusNegative = ws('Compute -5/6 + -1/4.', '-13/12');
  assert.ok(minusNegative.steps.some((step) => step.includes('+ (-3)')), minusNegative.steps.join('\n'));
  const zero = ws('Subtract: 3/5 - 3/5', '0');
  assert.equal(zero.steps.at(-1), 'So $\\frac{3}{5} - \\frac{3}{5} = 0$.');
  assert.equal(zero.answerSummary, 'The answer is $0$.');
});

test('it returns null, never a wrong step, for what it cannot work exactly', () => {
  const ws = fractions.workedSolution;
  // Owned, but nothing to work: the answer's form only.
  assert.ok(fractions.matches({ type: 'fraction', prompt: 'Write the part shaded.', answer: '3/4' }));
  assert.equal(ws({ type: 'fraction', prompt: 'Write the part shaded.', answer: '3/4' }), null);
  assert.equal(ws({ type: 'fraction', prompt: 'Simplify.', answer: '3/4' }), null);
  // An authored key the operands are not worth: no steps toward another number.
  assert.ok(ws({ type: 'fraction', prompt: 'Add.', n1: 1, d1: 3, n2: 1, d2: 2 }));
  assert.equal(ws({ type: 'fraction', prompt: 'Add.', n1: 1, d1: 3, n2: 1, d2: 2, ansNum: 2, ansDen: 5 }), null);
  // Not a fraction question at all.
  assert.equal(ws({ type: 'multiAnswer', prompt: 'Solve 2x = 6.', answerFields: [{ id: 'x', answer: '3' }] }), null);
  assert.equal(ws(null), null);
});

test('the closed review shows these steps when the item has none of its own', () => {
  const question = ITEMS.find((item) => item.label.startsWith('authored Subtract 1/4 from 5/6')).question;
  const review = buildClosedQuestionReview({ question });
  assert.equal(review.fromFamily, true);
  assert.deepEqual(review.authored.reasoning, fractions.workedSolution(question).steps);
  assert.equal(review.authored.answerSummary, 'The answer is $\\frac{7}{12}$.');
});

test('it is reachable only from the closed review: no hint, back-up or sibling path calls it', () => {
  const source = executableSource(readFileSync(new URL('src/platform/supports/families/fractions.js', ROOT), 'utf8'));
  const sectionStart = source.indexOf('const SLOPPY =');
  assert.ok(sectionStart > 0, 'the worked-solution section');
  for (const name of ['export const hints', 'export const backUpQuestion', 'export const similarProblem', 'export const expectedValues', 'export const matches']) {
    const at = source.indexOf(name);
    assert.ok(at > 0 && at < sectionStart, `${name} comes before the worked solution`);
  }
  assert.doesNotMatch(source.slice(0, sectionStart), /workedSolution|gradedSpelling|workedArithmetic|workedSimplify/, 'an open-item path calls the worked solution');
  assert.deepEqual([...source.slice(sectionStart).matchAll(/export const (\w+)/g)].map((match) => match[1]), ['workedSolution']);
});
