/*
 * THE "SYSTEMS" SUPPORT FAMILY, ON REAL ITEMS
 * (src/platform/supports/families/systems.js).
 *
 * Every item here is a question the classroom actually renders:
 *   - platform family instances, built by the real resolver
 *     (resolveFamilyQuestionInstance): systems.elimination and
 *     systems.substitution on both their tools (system, multiAnswer), and
 *     systems.algebraic2x2 on the Systems Workspace — one solution, fractional
 *     intersections, and the mixed none/infinite/one case;
 *   - the family slot in SAMPLE_QUESTION_FAMILY_RECOVERY.json;
 *   - the legacy generator `system` items in SAMPLE_PRACTICE_WITH_DOL.json and
 *     SAMPLE_LOCAL_PERSISTENCE_RESUME_SOLUTION_QA.json, generated by the real
 *     problemGenerator;
 *   - the Systems Workspace linear and matrix items in SAMPLE_BATCH_A_DEEP_DIVE.json
 *     and SAMPLE_MISSING_MATH_TOOLS.json;
 *   - the certified V5 fixture "systems-substitution", compiled by the
 *     production compiler;
 *   - the A.5C Path templates (drafts/fidelity-v2/algebra1/A.5C.json),
 *     instantiated inside their own generator ranges.
 *
 * The answer each item is checked against is computed INDEPENDENTLY of the
 * family: from the family generator's own chosen point, or with the shared
 * graders' math (solveTwoLines, solve2x2System, solveAlgebraicSystem).
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import * as systems from '../../src/platform/supports/families/systems.js';
import { familyFor } from '../../src/platform/supports/families/index.js';
import { buildQuestionHints } from '../../src/platform/supports/hints/questionHints.js';
import { buildSimilarWorkedExample } from '../../src/platform/supports/workedExample/similarProblem.js';
import { backUpStepFor } from '../../src/platform/supports/feedback/backUpStep.js';
import { generateQuestion } from '../../src/problemGenerator.js';
import { compileCapabilityFixture } from '../../src/platform/certification/capabilityFixtureRuntime.js';
import { INTERACTIVE_CAPABILITY_FIXTURES } from '../../src/platform/certification/interactiveCapabilityManifest.js';
import { hintRevealsAnswer } from '../../functions/shared/pathSolutionSupport.mjs';
import { resolveFamilyQuestionInstance } from '../../functions/shared/questionFamilyInstance.mjs';
import { solveTwoLines } from '../../functions/shared/toolMath/shared/toolMath.mjs';
import { solve2x2System } from '../../functions/shared/toolMath/systemsWorkspace/systemsMath.mjs';
import {
  linearEquationCoefficients,
  normalizeAlgebraicSystemConfig,
  solveAlgebraicSystem,
} from '../../functions/shared/toolMath/systemsWorkspace/algebraicSystemsEngine.mjs';
import { latexToExpression } from '../../functions/shared/algebra/latexToExpression.mjs';
import { evaluate } from '../../functions/shared/algebra/safeMath.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const readJson = (relative) => JSON.parse(fs.readFileSync(path.join(root, relative), 'utf8'));

/* --------------------------------------------- independent answers */

const near = (a, b) => Math.abs(a - b) < 1e-6;
// Every way the test itself would write a coordinate: integer, a/b, decimals.
const numberForms = (value) => {
  const forms = new Set([String(Math.round(value * 1e4) / 1e4), String(Math.round(value * 100) / 100), String(Math.round(value * 10) / 10)]);
  for (let d = 1; d <= 12; d += 1) {
    const n = Math.round(value * d);
    if (near(n / d, value)) { forms.add(d === 1 ? String(n) : `${n}/${d}`); break; }
  }
  return [...forms];
};
const independentForms = (answer) => {
  if (!answer || answer.outcome !== 'point') return ['no solution', 'infinitely many'];
  const xs = numberForms(answer.x);
  const ys = numberForms(answer.y);
  return [...xs, ...ys, `(${xs[0]}, ${ys[0]})`, `(${xs[0]},${ys[0]})`];
};
const fromSolve = (solved) => (solved.type === 'one' ? { outcome: 'point', x: solved.x, y: solved.y } : { outcome: solved.type });

/* --------------------------------------------- the real items */

const allocation = (seat) => ({ seat, variant: 0, stride: 40, index: seat, basis: 'seated' });
const familyItems = (familyId, tool, extra, seats, label, authored = {}) => Array.from({ length: seats }, (_, seat) => {
  const slot = { questionId: `q-${label}`, type: tool, ...authored, questionFamily: { id: familyId, version: 1, tool, ...extra } };
  const resolved = resolveFamilyQuestionInstance({ question: slot, assignmentId: `a-systems-${label}`, storageIndex: 0, allocation: allocation(seat) });
  assert.equal(resolved.error, null, `${familyId} resolves`);
  const { values } = resolved.instance;
  // The generator's own point (elimination / substitution build the system FROM it),
  // or the grader's solve of the displayed equations (algebraic2x2).
  const answer = familyId !== 'systems.algebraic2x2'
    ? { outcome: 'point', x: values.x0, y: values.y0 }
    : fromSolve(solveAlgebraicSystem(normalizeAlgebraicSystemConfig(resolved.question).coefficients));
  return { name: `${label} #${seat}`, kind: label, question: resolved.question, answer };
});

const ITEMS = [
  ...familyItems('systems.elimination', 'system', {}, 8, 'elimination/system'),
  ...familyItems('systems.elimination', 'system', { constraints: { requireMatchingCoefficient: true } }, 6, 'elimination/system/matching'),
  ...familyItems('systems.elimination', 'multiAnswer', {}, 8, 'elimination/multiAnswer'),
  ...familyItems('systems.substitution', 'system', {}, 8, 'substitution/system'),
  ...familyItems('systems.substitution', 'multiAnswer', {}, 8, 'substitution/multiAnswer'),
  ...familyItems('systems.algebraic2x2', 'systemsWorkspace', {}, 6, 'algebraic/one'),
  ...familyItems('systems.algebraic2x2', 'systemsWorkspace', { constraints: { solutionForm: 'fraction' } }, 6, 'algebraic/fraction'),
  ...familyItems('systems.algebraic2x2', 'systemsWorkspace', { constraints: { solutionCase: 'mixed' } }, 12, 'algebraic/mixed'),
  // The slot's own instructional choice of method.
  ...familyItems('systems.algebraic2x2', 'systemsWorkspace', {}, 4, 'algebraic/substitution', { method: 'substitution' }),
  ...familyItems('systems.algebraic2x2', 'systemsWorkspace', {}, 4, 'algebraic/elimination', { method: 'elimination' }),
];

// The family slot a sample assignment ships with.
{
  const sample = readJson('SAMPLE_QUESTION_FAMILY_RECOVERY.json');
  const slot = sample.sections.flatMap((section) => section.questions).find((question) => question.questionId === 'dol-system');
  for (let seat = 0; seat < 4; seat += 1) {
    const resolved = resolveFamilyQuestionInstance({ question: { ...slot, questionFamily: { ...slot.questionFamily, tool: 'system' } }, assignmentId: 'sample-recovery', storageIndex: 0, allocation: allocation(seat) });
    assert.equal(resolved.error, null);
    ITEMS.push({ name: `sample recovery dol-system #${seat}`, kind: 'sample/family', question: resolved.question, answer: { outcome: 'point', x: resolved.instance.values.x0, y: resolved.instance.values.y0 } });
  }
}

// The legacy generator's `system` items, generated as the browser generates them.
for (const [file, pick] of [
  ['SAMPLE_PRACTICE_WITH_DOL.json', (json) => json[1]],
  ['SAMPLE_LOCAL_PERSISTENCE_RESUME_SOLUTION_QA.json', (json) => json[4]],
]) {
  const blueprint = pick(readJson(file));
  assert.equal(blueprint.type, 'system');
  for (let variant = 0; variant < 5; variant += 1) {
    const question = generateQuestion(blueprint, `${file}|variant:${variant}`);
    const [l1, l2] = question.graph.functions;
    ITEMS.push({ name: `${file} variant ${variant}`, kind: 'legacy/generator', question, answer: fromSolve(solveTwoLines({ m1: l1.m, b1: l1.b, m2: l2.m, b2: l2.b })) });
  }
}

// Systems Workspace linear and matrix items from the sample assignments (raw stored shape: toolId).
{
  const batchA = readJson('SAMPLE_BATCH_A_DEEP_DIVE.json').questions;
  const missing = readJson('SAMPLE_MISSING_MATH_TOOLS.json').questions;
  ITEMS.push(
    { name: 'batch A linear', kind: 'workspace/linear', question: batchA[3], answer: fromSolve(solveTwoLines(batchA[3].system)) },
    { name: 'missing tools linear (no mode)', kind: 'workspace/linear', question: missing[2], answer: fromSolve(solveTwoLines(missing[2].system)) },
    { name: 'batch A matrix', kind: 'workspace/matrix', question: batchA[6], answer: fromSolve(solve2x2System(batchA[6].matrix)) },
  );
}

// The certified V5 substitution fixture, through the production compiler.
{
  const question = compileCapabilityFixture(INTERACTIVE_CAPABILITY_FIXTURES.find((fixture) => fixture.id === 'systems-substitution'));
  ITEMS.push({ name: 'V5 systems-substitution fixture', kind: 'workspace/algebraic-authored', question, answer: fromSolve(solveAlgebraicSystem(normalizeAlgebraicSystemConfig(question).coefficients)) });
}

// The A.5C Path templates, instantiated inside their own generator ranges.
{
  const documents = readJson('drafts/fidelity-v2/algebra1/A.5C.json').documents;
  const fill = (template, values) => JSON.parse(JSON.stringify(template).replace(/\{\{(\w+)(\|signed)?\}\}/g, (match, name, signed) => {
    const value = values[name];
    return signed ? (value < 0 ? `- ${-value}` : `+ ${value}`) : String(value);
  }));
  const asNumbers = (question) => ({ ...question, system: Object.fromEntries(Object.entries(question.system).map(([key, value]) => [key, Number(value)])) });
  const workspace = documents.find((document) => document.id === 'mm_A_5C_v2_systems-workspace');
  [[1, -2, 3, 4], [4, -1, -3, -6], [2, -5, 0, 7]].forEach(([m1, m2, x, b1]) => {
    const y = m1 * x + b1;
    const question = asNumbers(fill(workspace, { m1, m2, x, b1, y, b2: y - m2 * x }));
    ITEMS.push({ name: `A.5C systems-workspace m1=${m1} m2=${m2}`, kind: 'workspace/linear', question, answer: fromSolve(solveTwoLines(question.system)) });
  });
  const identical = documents.find((document) => document.id === 'mm_A_5C_v2_classify-identical');
  [[3, -2], [-1, 5]].forEach(([m, b]) => {
    const question = asNumbers(fill(identical, { m, b }));
    ITEMS.push({ name: `A.5C classify-identical m=${m} b=${b}`, kind: 'workspace/linear-special', question, answer: fromSolve(solveTwoLines(question.system)) });
  });
}

const guardFor = (item) => [...systems.expectedValues(item.question), ...independentForms(item.answer)];

/* --------------------------------------------- checking a worked sibling */

const mathSegments = (value) => [...String(value).matchAll(/\$([^$]+)\$/g)].map((match) => match[1]);
const plainMath = (latex) => latexToExpression(latex).replace(/·/g, '*');
// Every $…$ equation (or chain a = b = c) in the worked steps is TRUE at the
// sibling's own solution: the work, not only the answer, is right.
const assertStepsTrue = (example, point, label) => {
  const scope = { x: point.x, y: point.y };
  let checked = 0;
  example.steps.forEach((step) => mathSegments(step).forEach((segment) => {
    const parts = segment.split('=');
    if (parts.length < 2) return;
    const values = parts.map((part) => Number(evaluate(plainMath(part), scope)));
    values.slice(1).forEach((value) => assert.ok(near(value, values[0]), `${label}: "${segment}" is not true at (${point.x}, ${point.y}) in "${step}"`));
    checked += 1;
  }));
  assert.ok(checked >= 3, `${label}: the worked steps show their equations`);
};
// The sibling's own system, read back from its prompt and solved here.
const siblingSystem = (example) => {
  const rows = [...example.prompt.matchAll(/\[(-?\d+)\s+(-?\d+)\s*\|\s*(-?\d+)\]/g)].map((match) => match.slice(1).map(Number));
  if (rows.length === 2) return rows.map(([a, b, c]) => ({ a, b, c }));
  return mathSegments(example.prompt).filter((segment) => segment.includes('=')).map((segment) => linearEquationCoefficients(plainMath(segment)));
};
const solveRows = ([r1, r2]) => {
  const det = r1.a * r2.b - r1.b * r2.a;
  return { x: (r1.c * r2.b - r1.b * r2.c) / det, y: (r1.a * r2.c - r1.c * r2.a) / det, det };
};

/* ---------------------------------------------------------------- tests */

test('the corpus covers every sub-kind the family claims', () => {
  const kinds = new Set(ITEMS.map((item) => item.kind));
  ['elimination/system', 'elimination/multiAnswer', 'substitution/system', 'substitution/multiAnswer', 'algebraic/one', 'algebraic/fraction',
    'algebraic/mixed', 'legacy/generator', 'workspace/linear', 'workspace/matrix', 'workspace/algebraic-authored', 'workspace/linear-special']
    .forEach((kind) => assert.ok(kinds.has(kind), `corpus has ${kind}`));
  const outcomes = new Set(ITEMS.filter((item) => item.kind === 'algebraic/mixed').map((item) => item.answer.outcome));
  assert.deepEqual([...outcomes].sort(), ['infinite', 'none', 'point'], 'the mixed slot delivers all three outcomes');
  assert.ok(ITEMS.length >= 90);
});

test('every real item is owned by this family, and only by this family', () => {
  for (const item of ITEMS) {
    assert.equal(systems.matches(item.question), true, item.name);
    assert.equal(familyFor(item.question), systems, `${item.name}: no earlier family claims it`);
  }
});

test('what is not two linear equations is not claimed', () => {
  const batchA = readJson('SAMPLE_BATCH_A_DEEP_DIVE.json').questions;
  const slope = resolveFamilyQuestionInstance({
    question: { questionId: 'q-slope', type: 'multiAnswer', questionFamily: { id: 'linear.slopeFromPoints', version: 1, tool: 'multiAnswer' } },
    assignmentId: 'a-negative', storageIndex: 0, allocation: allocation(0),
  }).question;
  const literalSystem = readJson('src/demo/demoAssignmentBank.json')[2].questions[2];
  const notOurs = [
    ['inequalities workspace', batchA[4]],
    ['linear-quadratic workspace', batchA[5]],
    ['3×3 matrix', { type: 'systemsWorkspace', mode: 'matrix3', matrix: { rows: [[1, 1, 1, 6], [2, -1, 1, 3], [1, 2, -1, 2]] } }],
    ['3×3 algebraic', { type: 'systemsWorkspace', mode: 'algebraic', equations: ['x + y + z = 6', '2x - y + z = 3', 'x + 2y - z = 2'], variables: ['x', 'y', 'z'] }],
    ['slope multiAnswer', slope],
    ['one-equation multiAnswer with a pair answer', { type: 'multiAnswer', prompt: 'Find the y-intercept of $3x + 4y = 24$.', answerFields: [{ id: 'p', answer: '(0, 6)' }] }],
    ['two equations, but the pair does not solve them', { type: 'multiAnswer', prompt: 'Is $(1, 1)$ on $y = 2x$ and on $y = x + 3$?', answerFields: [{ id: 'p', answer: '(1, 1)' }] }],
    ['literal system (owned by linearEquations)', literalSystem],
    ['step algebra', { type: 'stepAlgebra', equation: '3x + 5 = 20' }],
  ];
  for (const [name, question] of notOurs) assert.equal(systems.matches(question), false, name);
  // …while a hand-authored multiAnswer system with no family id is recognised by content.
  assert.equal(systems.matches({ type: 'multiAnswer', prompt: 'Solve the system $x + y = 5$ and $x - y = 1$.', answerFields: [{ id: 'xy', label: '$(x, y)$ =', answer: '(3, 2)' }] }), true);
  assert.equal(systems.matches({ type: 'multiAnswer', prompt: 'Solve $2x + y = 7$ and $x - y = 2$.', answerFields: [{ id: 'x', label: 'x', answer: '3' }, { id: 'y', label: 'y', answer: '1' }] }), true);
});

test('expectedValues carries the answer in every form a hint could leak', () => {
  for (const item of ITEMS) {
    const values = systems.expectedValues(item.question);
    if (item.answer.outcome === 'point') {
      const [x] = numberForms(item.answer.x);
      const [y] = numberForms(item.answer.y);
      assert.ok(values.includes(x) && values.includes(y), `${item.name}: bare coordinates ${x}, ${y} in ${JSON.stringify(values)}`);
      assert.ok(values.includes(`(${x}, ${y})`), `${item.name}: the pair (${x}, ${y})`);
    }
    if (item.question.type === 'systemsWorkspace' || item.question.toolId === 'systemsWorkspace' || item.answer.outcome !== 'point') {
      // Every outcome phrase, whichever is right, so the guard's silence tells nothing.
      systems.OUTCOME_PHRASES.forEach((phrase) => assert.ok(values.includes(phrase), `${item.name}: ${phrase}`));
    }
  }
});

test('hints: 2–4 sentences from this problem, none of which names or narrows the answer', () => {
  let specific = 0;
  for (const item of ITEMS) {
    const hints = systems.hints(item.question);
    assert.ok(hints.length >= 2 && hints.length <= 4, `${item.name}: ${hints.length} hints`);
    const guard = guardFor(item);
    hints.forEach((hint) => {
      assert.equal(typeof hint, 'string');
      assert.equal(hintRevealsAnswer(hint, guard), false, `${item.name}: "${hint}" leaks the answer`);
      systems.OUTCOME_PHRASES.forEach((phrase) => assert.ok(!hint.toLowerCase().includes(phrase), `${item.name}: "${hint}" names an outcome`));
    });
    // Built from this problem: at least one hint quotes one of its equations.
    if (hints.some((hint) => /\$[^$]*=[^$]*\$/.test(hint))) specific += 1;
    // The platform ladder carries them (after the leak guard).
    const ladder = buildQuestionHints(item.question).filter((hint) => hint.source === 'family').map((hint) => hint.text);
    hints.forEach((hint) => assert.ok(ladder.includes(hint), `${item.name}: buildQuestionHints keeps "${hint}"`));
  }
  assert.ok(specific >= ITEMS.length * 0.8, `most hint ladders quote the problem's own equations (${specific}/${ITEMS.length})`);
});

test('hints read what the student sees, not the outcome: every mixed-case system gets the same advice about cancelling', () => {
  const mixed = ITEMS.filter((item) => item.kind === 'algebraic/mixed');
  const special = 'If both variables cancel, decide whether the statement that is left is true or false';
  for (const item of mixed) {
    assert.ok(systems.hints(item.question).some((hint) => hint.includes(special)), `${item.name} (${item.answer.outcome})`);
  }
  // A one-solution `system` item is never told about cancelling variables.
  const plain = ITEMS.find((item) => item.kind === 'elimination/system');
  assert.ok(!systems.hints(plain.question).some((hint) => hint.includes(special)));
});

test('a hint whose numbers coincide with the answer falls back to a wording without them', () => {
  // 2x - y = 0 holds the 2 of (1, 2): the quoted equation would name a coordinate.
  const question = { type: 'system', prompt: 'Solve the system.', equationsLatex: ['x + y = 3', '2x - y = 0'], solution: [1, 2] };
  const hints = systems.hints(question);
  assert.equal(hints.length, 4);
  hints.forEach((hint) => assert.equal(hintRevealsAnswer(hint, ['1', '2', '(1, 2)']), false, hint));
  assert.ok(hints.some((hint) => hint.includes('$y$-terms') && hint.includes('opposites')), 'still names this problem’s move');
});

test('similarProblem: a fully worked sibling with different numbers and a different, correct answer', () => {
  for (const item of ITEMS) {
    const example = systems.similarProblem(item.question, { seed: 0 });
    assert.ok(example, `${item.name}: a sibling`);
    assert.ok(example.prompt && example.steps.length >= 4 && example.answer, item.name);
    // Its answer, recomputed here from its own equations.
    const rows = siblingSystem(example);
    assert.equal(rows.length, 2, `${item.name}: the sibling shows two equations`);
    const solved = solveRows(rows);
    assert.notEqual(solved.det, 0, `${item.name}: one solution`);
    const pair = example.answer.match(/^\((-?\d+), (-?\d+)\)$/);
    assert.ok(pair, `${item.name}: answer "${example.answer}" is a pair`);
    const point = { x: Number(pair[1]), y: Number(pair[2]) };
    assert.ok(near(point.x, solved.x) && near(point.y, solved.y), `${item.name}: ${example.answer} solves the sibling`);
    assertStepsTrue(example, point, item.name);
    // Never this problem: a different answer, and no step names this one.
    if (item.answer.outcome === 'point') assert.ok(!(near(point.x, item.answer.x) && near(point.y, item.answer.y)), `${item.name}: a different answer`);
    const guard = guardFor(item);
    [example.prompt, ...example.steps, example.answer].forEach((piece) => assert.equal(hintRevealsAnswer(piece, guard), false, `${item.name}: "${piece}" names this answer`));
    // Deterministic from the seed, different for another seed.
    assert.deepEqual(systems.similarProblem(item.question, { seed: 0 }), example);
    assert.notDeepEqual(systems.similarProblem(item.question, { seed: 1 }), example, `${item.name}: another seed, another sibling`);
    assert.ok(buildSimilarWorkedExample(item.question), `${item.name}: the platform offers it`);
  }
});

test('the sibling is the same kind of problem', () => {
  const kindOf = (item) => systems.similarProblem(item.question, { seed: 2 });
  for (const item of ITEMS) {
    const example = kindOf(item);
    if (item.kind.startsWith('substitution/')) assert.match(example.steps[0], /already gives \$y = /, item.name);
    if (item.kind === 'legacy/generator') assert.match(example.steps[0], /set the right sides equal/, item.name);
    if (item.kind.startsWith('elimination/')) assert.match(example.steps[0], /^Line up the equations/, item.name);
    if (item.kind.startsWith('workspace/linear')) assert.match(example.prompt, /^Graph /, item.name);
    if (item.kind === 'workspace/matrix') assert.match(example.prompt, /augmented matrix/, item.name);
    if (item.kind === 'algebraic/substitution') assert.match(example.prompt, /by substitution/, item.name);
  }
});

test('backUpQuestion: two choices about this problem’s first move, the conventional one correct, no answer in it', () => {
  let specific = 0;
  for (const item of ITEMS) {
    const step = systems.backUpQuestion(item.question);
    assert.ok(step, item.name);
    assert.equal(step.options.length, 2, item.name);
    assert.notEqual(step.options[0], step.options[1], item.name);
    assert.ok(step.options.includes(step.correct), `${item.name}: the correct option is offered`);
    const guard = guardFor(item);
    [step.prompt, ...step.options].forEach((piece) => assert.equal(hintRevealsAnswer(piece, guard), false, `${item.name}: "${piece}"`));
    assert.ok(!/\$/.test(step.prompt + step.options.join('')), `${item.name}: plain text (the buttons do not render math)`);
    if (!step.prompt.includes('Does the solution of a system')) specific += 1;
    assert.equal(backUpStepFor(item.question).source, 'family', `${item.name}: the inclusion step uses it`);
  }
  assert.ok(specific >= ITEMS.length * 0.9, `most back-up steps are about this problem (${specific}/${ITEMS.length})`);
});

test('the back-up step points the right way for each first move', () => {
  const opposite = systems.backUpQuestion({ type: 'system', equationsLatex: ['2x + 3y = 12', '5x - 3y = 9'], solution: [3, 2] });
  assert.equal(opposite.correct, 'Add the two equations');
  const same = systems.backUpQuestion({ type: 'system', equationsLatex: ['4x + 3y = 25', '2x + 3y = 17'], solution: [4, 3] });
  assert.equal(same.correct, 'Subtract the second equation from the first');
  const multiply = systems.backUpQuestion({ type: 'system', equationsLatex: ['x + 2y = 7', '3x - 5y = -1'], solution: [3, 2] });
  assert.equal(multiply.correct, 'Every term, on both sides');
  const substitution = systems.backUpQuestion({ type: 'system', equationsLatex: ['y = 2x - 1', '3x + 2y = 33'], solution: [5, 9] });
  assert.equal(substitution.correct, 'Replace y with (2x - 1)');
  const setEqual = systems.backUpQuestion({ type: 'system', equationsLatex: ['y = -4x + 23', 'y = 4x - 25'], solution: [6, -1] });
  assert.equal(setEqual.correct, 'Set -4x + 23 equal to 4x - 25');
});
