/*
 * THE "FRACTIONS" SUPPORT FAMILY, ON REAL ITEMS
 * (src/platform/supports/families/fractions.js).
 *
 * The sample corpus (teacher-import-jsons, SAMPLE_*.json, the district DOL)
 * holds no fraction arithmetic — that is asserted below, so the family is
 * proven not to claim any of it. Every item it does own is built the way the
 * classroom builds it:
 *   - fraction DRILLS generated by the real problemGenerator, on the pinned
 *     generation keys of tests/platform/fractionQuestion.test.mjs, with the
 *     default and an authored denominator set;
 *   - authored SUMS (n1/d1 + n2/d2) compiled by the production V5 compiler
 *     (studentActions: ['fractionAnswer']) and generated;
 *   - SIMPLIFY items: the assignment-local Question Family slot, the Path-style
 *     template slot and the authored 2/4 key of the browser fixture
 *     (tests/browser/fractionTemplateGradingFixture.mjs), drawn for real seats,
 *     plus V5-compiled "Simplify 6/8." and "Simplify." over the line \frac{6}{8} =;
 *   - authored ARITHMETIC (+ − × ÷, symbols and words) compiled by V5;
 *   - multiAnswer items compiled by V5 (studentActions: ['multipleResponses']);
 *   - FORM items the family owns but cannot read numbers from.
 *
 * Every answer the leak checks use is computed HERE, independently of the
 * family (from the operands with the test's own rational arithmetic, or from
 * the prompt with the test's own regex), and joined with the family's own
 * expectedValues. Every sibling is re-evaluated by the test's own LaTeX
 * evaluator: its prompt against its answer, and every "a = b = c" in its steps.
 */
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import * as fractions from '../../src/platform/supports/families/fractions.js';
import { familyFor } from '../../src/platform/supports/families/index.js';
import { buildQuestionHints, questionAnswerValues } from '../../src/platform/supports/hints/questionHints.js';
import { buildSimilarWorkedExample } from '../../src/platform/supports/workedExample/similarProblem.js';
import { backUpStepFor } from '../../src/platform/supports/feedback/backUpStep.js';
import { generateQuestion } from '../../src/problemGenerator.js';
import { parseAssignmentBlueprintText, validateAssignmentQuestions } from '../../src/assignmentBlueprint.js';
import { compileAuthoringIntentV5 } from '../../src/platform/contract/authoringIntentV5.js';
import { hintRevealsAnswer } from '../../functions/shared/pathSolutionSupport.mjs';
import { isWrittenInLowestTerms } from '../../functions/shared/fractionAnswer.mjs';
import { gradeFractionResponse } from '../../functions/shared/ordinaryResponseGrading.mjs';
import { resolveFamilyQuestionInstance } from '../../functions/shared/questionFamilyInstance.mjs';
import { listPlatformQuestionFamilies } from '../../functions/shared/questionFamilyRegistry.mjs';
import { questionFor, generationKeyFor, familyContextFor } from '../browser/fractionTemplateGradingFixture.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');

/* --------------------------------------------- the test's own arithmetic */

const gcd = (a, b) => (b === 0 ? Math.abs(a) : gcd(b, a % b));
const frac = (n, d) => {
  assert.notEqual(d, 0, 'no zero denominator');
  const sign = d < 0 ? -1 : 1;
  const g = gcd(n, d) || 1;
  return { n: (sign * n) / g, d: (sign * d) / g };
};
const OPS = {
  '+': (a, b) => frac(a.n * b.d + b.n * a.d, a.d * b.d),
  '-': (a, b) => frac(a.n * b.d - b.n * a.d, a.d * b.d),
  '×': (a, b) => frac(a.n * b.n, a.d * b.d),
  '÷': (a, b) => frac(a.n * b.d, a.d * b.n),
};
const same = (a, b) => a.n === b.n && a.d === b.d;
const show = (v) => (v.d === 1 ? String(v.n) : `${v.n}/${v.d}`);

/** Every way the test itself would write a value: a/b, \frac, decimals, and an unreduced key. */
const independentForms = (value, ...unreduced) => {
  const forms = new Set([show(value)]);
  if (value.d !== 1) {
    forms.add(`${value.n < 0 ? '-' : ''}\\frac{${Math.abs(value.n)}}{${value.d}}`);
    forms.add(String(Math.round((value.n / value.d) * 100) / 100));
    forms.add(String(Math.round((value.n / value.d) * 1000) / 1000));
  }
  for (const [n, d] of unreduced) forms.add(`${n}/${d}`).add(`\\frac{${n}}{${d}}`);
  return [...forms];
};

/*
 * A small LaTeX evaluator, written for this test: numbers, \frac{…}{…},
 * + − \times \div, parentheses and unary minus, exactly.
 */
const evaluateLatex = (source) => {
  const s = source.replace(/\\left|\\right/g, '').replace(/\s+/g, '');
  let i = 0;
  const peek = (literal) => s.startsWith(literal, i);
  const expect = (literal) => {
    assert.ok(peek(literal), `expected ${literal} at ${i} in ${source}`);
    i += literal.length;
  };
  const expression = () => {
    let value = term();
    while (peek('+') || peek('-')) {
      const op = s[i];
      i += 1;
      value = OPS[op](value, term());
    }
    return value;
  };
  const term = () => {
    let value = factor();
    for (;;) {
      if (peek('\\times')) { i += 6; value = OPS['×'](value, factor()); }
      else if (peek('\\div')) { i += 4; value = OPS['÷'](value, factor()); }
      else return value;
    }
  };
  const factor = () => {
    if (peek('-')) { i += 1; const inner = factor(); return frac(-inner.n, inner.d); }
    if (peek('(')) { i += 1; const inner = expression(); expect(')'); return inner; }
    if (peek('\\frac{')) {
      i += 6;
      const top = expression();
      expect('}{');
      const bottom = expression();
      expect('}');
      return OPS['÷'](top, bottom);
    }
    const digits = /^\d+/.exec(s.slice(i));
    assert.ok(digits, `a number at ${i} in ${source}`);
    i += digits[0].length;
    return frac(Number(digits[0]), 1);
  };
  const value = expression();
  assert.equal(i, s.length, `the whole of ${source} was read`);
  return value;
};
const mathSegments = (line) => [...String(line).matchAll(/\$([^$]+)\$/g)].map((match) => match[1]);

/** Re-check a worked sibling: its prompt's value IS its answer, and every equality in its steps holds. */
const verifySibling = (sibling, { kind, op }, label) => {
  assert.ok(sibling, `${label}: a sibling`);
  assert.ok(sibling.steps.length >= 2, `${label}: worked in steps`);
  const answer = evaluateLatex(sibling.answer.replace('/', '\\div'));
  const [expression] = mathSegments(sibling.prompt);
  assert.ok(expression, `${label}: the sibling prompt shows its problem`);
  assert.equal(evaluateLatex(expression).n * answer.d, answer.n * evaluateLatex(expression).d, `${label}: ${sibling.prompt} is worth ${sibling.answer}`);
  if (kind === 'simplify') {
    assert.match(sibling.prompt, /^Simplify /, `${label}: a simplify sibling`);
    assert.ok(isWrittenInLowestTerms(sibling.answer), `${label}: ${sibling.answer} is in lowest terms`);
  } else {
    const symbol = { '+': '+', '-': '-', '×': '\\times', '÷': '\\div' }[op];
    assert.ok(expression.includes(symbol), `${label}: the sibling keeps the operation ${op}`);
    assert.ok(isWrittenInLowestTerms(sibling.answer), `${label}: the worked answer ${sibling.answer} is simplified`);
  }
  for (const step of sibling.steps) {
    for (const segment of mathSegments(step)) {
      if (!segment.includes('=')) continue;
      const sides = segment.split('=').map((side) => side.trim()).filter(Boolean).map(evaluateLatex);
      sides.forEach((side) => assert.ok(same(side, sides[0]), `${label}: ${segment} holds`));
    }
    const lcm = /least common multiple of \$(\d+)\$ and \$(\d+)\$ is \$(\d+)\$/.exec(step);
    if (lcm) assert.equal(Number(lcm[3]), (Number(lcm[1]) * Number(lcm[2])) / gcd(Number(lcm[1]), Number(lcm[2])), `${label}: ${step}`);
    const gcf = /greatest common factor of the numerator \$(\d+)\$ and the denominator \$(\d+)\$: it is \$(\d+)\$/.exec(step);
    if (gcf) assert.equal(Number(gcf[3]), gcd(Number(gcf[1]), Number(gcf[2])), `${label}: ${step}`);
  }
  const last = sibling.steps.at(-1);
  const answerLatex = answer.d === 1 ? String(answer.n) : `\\frac{${answer.n}}{${answer.d}}`;
  assert.ok(last.includes(answerLatex), `${label}: the last step reaches ${answerLatex}`);
  return answer;
};

/* --------------------------------------------- the real items */

const KEYS = [
  'asg-1|student-a|0|variant:0',
  'asg-1|student-a|0|variant:1',
  'asg-1|student-b|0|variant:0',
  'asg-1|student-c|4|variant:0',
  'asg-2|shared|2|variant:0',
  'preview|teacher|7|variant:3',
  'demo-key',
  'asg-9|student-q|1|variant:0',
];

const ITEMS = [];
const owned = (name, kind, op, question, value, unreduced = []) => ITEMS.push({ name, kind, op, question, value, forms: independentForms(value, ...unreduced) });

// Drills: generated exactly as the browser generates them.
for (const blueprint of [{ type: 'fraction', prompt: 'Add the fractions.' }, { type: 'fraction', prompt: 'Add the fractions.', generator: { denominators: [2, 3, 4] } }]) {
  for (const key of KEYS) {
    const question = generateQuestion(blueprint, key);
    const { n1, d1, n2, d2 } = question;
    owned(`drill ${JSON.stringify(blueprint.generator || {})} @ ${key}`, 'sum', '+', question, OPS['+'](frac(n1, d1), frac(n2, d2)), [[n1 * d2 + n2 * d1, d1 * d2]]);
  }
}

const compileV5 = (questions) => {
  const parsed = parseAssignmentBlueprintText(JSON.stringify({
    schemaVersion: 5,
    assignment: { title: 'Fraction support family', courseId: 'algebra1' },
    sections: [{ role: 'practice', title: 'Practice', questions }],
  }));
  validateAssignmentQuestions(parsed.questions);
  return parsed.questions;
};

// Authored sums, compiled and generated. [n1, d1, n2, d2]: the answer 1 twice,
// so the guard has to drop a hint quoting \frac{1}{4} (it contains "1").
const SUMS = [[1, 2, 1, 3], [3, 8, 5, 8], [1, 4, 3, 4], [-1, 2, 1, 3], [-3, 4, 1, 4], [5, 6, 1, 4], [2, 3, 3, 4], [7, 10, 2, 5]];
compileV5(SUMS.map(([n1, d1, n2, d2]) => ({ standard: 'A.3C', prompt: 'Add.', studentActions: ['fractionAnswer'], n1, d1, n2, d2 })))
  .forEach((authored, index) => {
    const [n1, d1, n2, d2] = SUMS[index];
    const question = generateQuestion(authored, KEYS[index % KEYS.length]);
    assert.deepEqual([question.n1, question.d1, question.n2, question.d2], SUMS[index], 'the author\'s operands are kept');
    owned(`authored sum ${n1}/${d1} + ${n2}/${d2}`, 'sum', '+', question, OPS['+'](frac(n1, d1), frac(n2, d2)), [[n1 * d2 + n2 * d1, d1 * d2]]);
  });

// Simplify: the browser fixture's three slots, drawn for real seats.
const simplifyValue = (question) => {
  const [, n, d] = /^Simplify (\d+)\/(\d+)\.$/.exec(question.prompt);
  return frac(Number(n), Number(d));
};
for (const kind of ['family', 'template', 'authored']) {
  for (let seat = 0; seat < (kind === 'authored' ? 2 : 8); seat += 1) {
    const question = generateQuestion(questionFor(kind), generationKeyFor(seat), null, null, familyContextFor(kind));
    const [n, d] = question.answer.split('/').map(Number);
    owned(`simplify ${kind} seat ${seat}: ${question.prompt}`, 'simplify', null, question, simplifyValue(question), [[n, d]]);
  }
}
{
  const [plain, line] = compileV5([
    { standard: 'A.3C', prompt: 'Simplify 6/8.', studentActions: ['fractionAnswer'], answer: '3/4' },
    { standard: 'A.3C', prompt: 'Simplify.', studentActions: ['fractionAnswer'], answer: '3/4', expressionLatex: '\\frac{6}{8} =' },
  ]).map((question, index) => generateQuestion(question, KEYS[index]));
  owned('V5 Simplify 6/8.', 'simplify', null, plain, frac(6, 8));
  owned('V5 Simplify. over \\frac{6}{8} =', 'simplify', null, line, frac(6, 8));
}

// Authored arithmetic, compiled by V5. The test states each problem's operands itself.
const ARITHMETIC = [
  { prompt: 'Add 3/8 + 3/8.', answer: '6/8', op: '+', a: [3, 8], b: [3, 8] },
  { prompt: 'Subtract: $\\frac{5}{6} - \\frac{1}{4}$', answer: '7/12', op: '-', a: [5, 6], b: [1, 4] },
  { prompt: 'Subtract 1/4 from 5/6.', answer: '7/12', op: '-', a: [5, 6], b: [1, 4] },
  { prompt: 'Multiply $\\frac{2}{3} \\times \\frac{3}{4}$.', answer: '1/2', op: '×', a: [2, 3], b: [3, 4] },
  { prompt: 'Find the product of $\\frac{2}{3}$ and $\\frac{3}{5}$.', answer: '2/5', op: '×', a: [2, 3], b: [3, 5] },
  { prompt: 'Divide $\\frac{1}{2} \\div \\frac{1}{4}$.', answer: '2', op: '÷', a: [1, 2], b: [1, 4] },
  { prompt: 'Divide: 3/4 ÷ 3/8', answer: '2', op: '÷', a: [3, 4], b: [3, 8] },
  { prompt: 'Find the sum.', expressionLatex: '\\frac{2}{5} + \\frac{1}{10} =', answer: '1/2', op: '+', a: [2, 5], b: [1, 10] },
  { prompt: 'Subtract: $\\frac{1}{4} - \\frac{3}{4}$', answer: '-1/2', op: '-', a: [1, 4], b: [3, 4] },
  { prompt: 'Add $-1 + \\frac{1}{2}$.', answer: '-1/2', op: '+', a: [-1, 1], b: [1, 2] },
];
compileV5(ARITHMETIC.map(({ prompt, answer, expressionLatex }) => ({ standard: 'A.3C', prompt, studentActions: ['fractionAnswer'], answer, ...(expressionLatex ? { expressionLatex } : {}) })))
  .forEach((authored, index) => {
    const { prompt, op, a, b, answer } = ARITHMETIC[index];
    const question = generateQuestion(authored, KEYS[index % KEYS.length]);
    const value = OPS[op](frac(...a), frac(...b));
    assert.ok(gradeFractionResponse(question, answer).isCorrect, `precondition: ${prompt} is keyed ${answer}`);
    assert.ok(same(evaluateLatex(answer.replace('/', '\\div')), value), `precondition: ${answer} is worth ${show(value)}`);
    owned(`authored ${prompt}`, 'arithmetic', op, question, value);
  });

// multiAnswer items: one free-response field whose key is the result shown.
const MULTI = [
  { prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', label: 'Sum', answer: '5/6', op: '+', a: [1, 2], b: [1, 3] },
  { prompt: 'Find the difference.', label: '$\\frac{3}{4} - \\frac{1}{6} =$', answer: '7/12', op: '-', a: [3, 4], b: [1, 6] },
  { prompt: 'Multiply: $\\frac{4}{5} \\times \\frac{5}{6}$', label: 'Product', answer: '2/3', op: '×', a: [4, 5], b: [5, 6] },
  { prompt: 'Divide $\\frac{2}{3} \\div \\frac{4}{9}$.', label: 'Quotient', answer: '3/2', op: '÷', a: [2, 3], b: [4, 9] },
];
compileV5(MULTI.map(({ prompt, label, answer }) => ({ standard: 'A.3C', prompt, studentActions: ['multipleResponses'], responses: [{ id: 'result', label, answer }] })))
  .forEach((question, index) => {
    const { prompt, op, a, b } = MULTI[index];
    assert.equal(question.type, 'multiAnswer');
    owned(`multiAnswer ${prompt}`, 'arithmetic', op, question, OPS[op](frac(...a), frac(...b)));
  });
{
  const [question] = compileV5([{ standard: 'A.3C', prompt: 'Simplify $\\frac{12}{16}$.', studentActions: ['multipleResponses'], responses: [{ id: 'simplest', label: 'Simplest form', answer: '3/4' }] }]);
  owned('multiAnswer Simplify 12/16', 'simplify', null, question, frac(12, 16));
}

// Owned, but nothing to read: helped with the answer's form only.
const FORM_ITEMS = [
  ...compileV5([{ standard: 'A.3C', prompt: 'Write the part shaded.', studentActions: ['fractionAnswer'], answer: '3/4', acceptedAnswers: ['6/8'] }])
    .map((question) => ({ name: 'V5 Write the part shaded.', question, value: frac(3, 4) })),
  { name: 'catalog example "Simplify." (no numbers)', question: { type: 'fraction', prompt: 'Simplify.', answer: '3/4' }, value: frac(3, 4) },
  { name: 'Write 0.75 another way.', question: { type: 'fraction', prompt: 'Write 0.75 another way.', answer: '0.75' }, value: frac(3, 4) },
];

const byKind = (kind) => ITEMS.filter((item) => item.kind === kind);

/* --------------------------------------------- tests */

test('the corpus has every sub-kind several times over', () => {
  assert.ok(byKind('sum').length >= 20, 'drills and authored sums');
  assert.ok(byKind('simplify').length >= 15, 'simplify items');
  for (const op of ['+', '-', '×', '÷']) {
    assert.ok(ITEMS.filter((item) => item.kind === 'arithmetic' && item.op === op).length >= 2, `arithmetic ${op}`);
  }
  assert.ok(ITEMS.filter((item) => item.question.type === 'multiAnswer').length >= 5, 'multiAnswer items');
});

test('matches(): the family owns each real fraction item, and no earlier family takes it', () => {
  for (const { name, question } of [...ITEMS, ...FORM_ITEMS]) {
    assert.equal(fractions.matches(question), true, name);
    assert.equal(familyFor(question), fractions, `${name}: owned by fractions`);
  }
  for (const { name, question, kind, op } of ITEMS) {
    const model = fractions.fractionModel(question);
    assert.equal(model.kind, kind === 'sum' ? 'arithmetic' : kind, `${name}: read as ${kind}`);
    if (op) assert.equal(model.op, op, `${name}: operation`);
  }
  for (const { name, question } of FORM_ITEMS) assert.equal(fractions.fractionModel(question).kind, 'form', name);
});

test('matches(): nothing in the sample corpus or the platform families is claimed', () => {
  const walk = (dir) => fs.readdirSync(dir, { withFileTypes: true })
    .flatMap((entry) => (entry.isDirectory() ? walk(path.join(dir, entry.name)) : entry.name.endsWith('.json') ? [path.join(dir, entry.name)] : []));
  const files = [
    ...walk(path.join(root, 'teacher-import-jsons')),
    ...fs.readdirSync(root).filter((file) => /^SAMPLE_.*\.json$/.test(file)).map((file) => path.join(root, file)),
    path.join(root, 'drafts/district-dol2/assignment.json'),
  ];
  let seen = 0;
  for (const file of files) {
    const json = JSON.parse(fs.readFileSync(file, 'utf8'));
    let questions;
    try {
      questions = compileAuthoringIntentV5(json).package.sections.flatMap((section) => section.questions || []);
    } catch {
      questions = Array.isArray(json) ? json : json.questions || [];
    }
    for (const question of questions) {
      for (const version of [question, ...(question.variants || []).map((variant) => ({ ...question, ...variant }))]) {
        seen += 1;
        assert.equal(fractions.matches(version), false, `${path.basename(file)}: ${version.type} "${version.prompt}"`);
      }
    }
  }
  assert.ok(seen >= 150, `the corpus was read (${seen})`);

  let instances = 0;
  for (const family of listPlatformQuestionFamilies()) {
    for (const tool of Object.keys(family.tools || {})) {
      for (let seat = 0; seat < 4; seat += 1) {
        const resolved = resolveFamilyQuestionInstance({
          question: { questionId: 'q', type: tool, questionFamily: { id: family.id, version: family.version, tool } },
          assignmentId: 'a-fractions-precision', storageIndex: 0,
          allocation: { seat, variant: 0, stride: 40, index: seat, basis: 'seated' },
        });
        if (resolved.error) continue;
        instances += 1;
        const { familyInstance: _instance, questionFamily: _family, familyId: _id, ...bare } = resolved.question;
        assert.equal(fractions.matches(resolved.question), false, `${family.id} on ${tool}`);
        assert.equal(fractions.matches(bare), false, `${family.id} on ${tool}, read by content alone`);
      }
    }
  }
  assert.ok(instances >= 40, `platform family instances were built (${instances})`);
});

test('matches(): a multiAnswer item is claimed only on an unmistakable signal', () => {
  const field = (answer, extra = {}) => [{ id: 'r', label: 'Result', answer, ...extra }];
  const refused = [
    ['a variable expression', { type: 'multiAnswer', prompt: 'Solve $x/2 + 1/3 = 1$.', answerFields: field('4/3') }],
    ['a key that is not the result', { type: 'multiAnswer', prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', answerFields: field('2/5') }],
    ['a choice field', { type: 'multiAnswer', prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', answerFields: field('5/6', { options: ['5/6', '2/5'] }) }],
    ['two fields', { type: 'multiAnswer', prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', answerFields: [...field('5/6'), { id: 's', label: 'Again', answer: '5/6' }] }],
    ['a grouped expression', { type: 'multiAnswer', prompt: 'Evaluate $(\\frac{1}{2} + \\frac{1}{3}) \\times 2$.', answerFields: field('5/6') }],
    ['three terms', { type: 'multiAnswer', prompt: 'Add $\\frac{1}{2} + \\frac{1}{3} + \\frac{1}{6}$.', answerFields: field('1') }],
    ['a platform family instance', { type: 'multiAnswer', prompt: 'Add $\\frac{1}{2} + \\frac{1}{3}$.', answerFields: field('5/6'), familyInstance: { familyId: 'linear.slopeFromPoints' } }],
  ];
  for (const [label, question] of refused) assert.equal(fractions.matches(question), false, label);
});

test('expectedValues() covers every independent form of each answer', () => {
  for (const { name, question, forms } of ITEMS) {
    const expected = fractions.expectedValues(question);
    for (const form of forms.filter((value) => !/^\d*\.\d+$|^-?0?\.\d/.test(value))) {
      assert.ok(expected.includes(form) || expected.includes(form.replace(/^(-?)0\./, '$1.')), `${name}: ${form} is listed`);
    }
    // The platform guard reads them too.
    const guard = questionAnswerValues(question);
    for (const form of forms) assert.ok(guard.includes(form) || !expected.includes(form), `${name}: the guard reads ${form}`);
  }
});

test('hints(): 2–4 sentences, from this problem\'s own numbers, never the answer', () => {
  let numbered = 0;
  for (const { name, question, forms } of [...ITEMS, ...FORM_ITEMS.map((item) => ({ ...item, forms: independentForms(item.value) }))]) {
    const hints = fractions.hints(question);
    assert.ok(hints.length >= 2 && hints.length <= 4, `${name}: ${hints.length} hints`);
    const answers = [...fractions.expectedValues(question), ...forms];
    for (const hint of hints) {
      assert.ok(typeof hint === 'string' && hint.length > 20, `${name}: a sentence`);
      assert.equal(hintRevealsAnswer(hint, answers), false, `${name}: "${hint}" reveals an answer`);
    }
    // The platform's ladder carries them.
    const ladder = buildQuestionHints(question);
    for (const hint of hints) assert.ok(ladder.some((entry) => entry.text === hint && entry.source === 'family'), `${name}: the ladder shows "${hint}"`);
    if (hints.some((hint) => /\$\d+\$|\\frac\{/.test(hint))) numbered += 1;
  }
  assert.ok(numbered >= ITEMS.length - 4, `hints quote the problem's own numbers (${numbered}/${ITEMS.length})`);
});

test('hints(): a numbered hint that would contain the answer falls back to the plain spelling', () => {
  // 1/4 + 3/4 = 1: every hint quoting \frac{1}{4} contains "1".
  const question = ITEMS.find((item) => item.name === 'authored sum 1/4 + 3/4').question;
  const hints = fractions.hints(question);
  assert.ok(hints.every((hint) => !hint.includes('\\frac{1}{4}')), 'no hint quotes 1/4');
  assert.match(hints[0], /same denominator/);
  // -1 + 1/2 = -1/2: a hint quoting \frac{1}{2} would leave only the sign to find.
  const negative = ITEMS.find((item) => item.name === 'authored Add $-1 + \\frac{1}{2}$.').question;
  assert.ok(fractions.expectedValues(negative).includes('\\frac{1}{2}'), 'the size of a negative answer is guarded');
  assert.ok(fractions.hints(negative).every((hint) => !hint.includes('\\frac{1}{2}')), 'no hint quotes 1/2');
  // 3/8 + 5/8 = 1 quotes its numbers: none of them is the answer.
  assert.match(fractions.hints(ITEMS.find((item) => item.name === 'authored sum 3/8 + 5/8').question)[0], /\\frac\{3\}\{8\}/);
});

test('similarProblem(): a different problem of the same kind, worked correctly, with a different answer', () => {
  for (const { name, kind, op, question, value } of ITEMS) {
    const answers = [...questionAnswerValues(question), ...independentForms(value)];
    for (const seed of [0, 1, 7]) {
      const sibling = fractions.similarProblem(question, { seed });
      const siblingValue = verifySibling(sibling, { kind, op }, `${name} seed ${seed}`);
      assert.ok(!same(siblingValue, value), `${name}: the sibling's ${sibling.answer} is not this answer ${show(value)}`);
      assert.notEqual(sibling.prompt, question.prompt);
      for (const step of sibling.steps) assert.equal(hintRevealsAnswer(step, answers), false, `${name}: "${step}"`);
      assert.deepEqual(fractions.similarProblem(question, { seed }), sibling, `${name}: deterministic for seed ${seed}`);
    }
    const offered = buildSimilarWorkedExample(question, { seed: 3 });
    assert.ok(offered, `${name}: the platform offers the sibling`);
    assert.ok(!same(verifySibling(offered, { kind, op }, `${name} (platform)`), value), `${name}: the offered sibling's answer differs`);
  }
  for (const { name, question } of FORM_ITEMS) {
    assert.equal(fractions.similarProblem(question, { seed: 0 }), null, name);
    assert.equal(buildSimilarWorkedExample(question), null, name);
  }
});

test('backUpQuestion(): a two-way choice about this problem\'s first move, never its answer', () => {
  for (const { name, question, forms } of ITEMS) {
    const step = fractions.backUpQuestion(question);
    assert.ok(step, name);
    assert.equal(step.options.length, 2, name);
    assert.ok(step.options.includes(step.correct), `${name}: the correct move is offered`);
    const answers = [...fractions.expectedValues(question), ...forms];
    for (const piece of [step.prompt, ...step.options]) assert.equal(hintRevealsAnswer(piece, answers), false, `${name}: "${piece}"`);
    const shown = backUpStepFor(question);
    assert.equal(shown.source, 'family', `${name}: the inclusion step uses it`);
    assert.equal(shown.correct, step.correct);
  }
  // The conventional first move for each kind.
  const correctFor = (name) => fractions.backUpQuestion(ITEMS.find((item) => item.name === name).question).correct;
  assert.equal(correctFor('authored Subtract: $\\frac{5}{6} - \\frac{1}{4}$'), 'Rewrite both over a common denominator');
  assert.equal(correctFor('authored Add 3/8 + 3/8.'), 'Keep the denominator the same');
  assert.equal(correctFor('authored Multiply $\\frac{2}{3} \\times \\frac{3}{4}$.'), 'No: multiply straight across');
  assert.equal(correctFor('authored Divide $\\frac{1}{2} \\div \\frac{1}{4}$.'), 'Turn the second fraction upside down and multiply');
  assert.equal(correctFor('V5 Simplify 6/8.'), 'Divide the top and bottom by the same number');
  // The correct move is not always first.
  assert.ok(new Set(ITEMS.map(({ question }) => fractions.backUpQuestion(question).options.indexOf(fractions.backUpQuestion(question).correct))).size === 2);
  for (const { name, question } of FORM_ITEMS) {
    assert.equal(fractions.backUpQuestion(question), null, name);
    assert.equal(backUpStepFor(question).source, 'platform', name);
  }
});
