/*
 * QUESTIONS WHOSE RECAP KEEPS ITS ANSWER TO ITSELF.
 *
 * A recap entry shows the correct answer and the worked solution, and it
 * stays. Most bank templates generate 13 or more distinct questions in 30
 * draws, so last week's answer is no key to this week's question. These
 * generate fewer than 8: the same question comes back, a retention re-check
 * included, and a stored answer would be its key. Their recap entries keep the
 * question and the student's own answer and leave out the correct answer and
 * the solution (pathSessionRecap.mjs).
 *
 * tests/platform/pathRecapWithheld.test.mjs regenerates this list from
 * seed/pathQuestionBank (30 seeded draws per template, compared by content)
 * and fails when it drifts. Student push J widened 26 of D's 27. The one left,
 * mm_A_12A_v2_mapping-nonfunction, has the same answer ("not a function") on
 * every draw, so however its wording varied, a recap would be the key.
 *
 * A second, named list holds templates whose draws differ in wording more
 * than in mathematics: they reach 8 distinct questions, but their answers
 * repeat as often as a repeating template's would. Their recap withholds too.
 */

export const RECAP_INSTANCE_DRAWS = 30;
export const RECAP_MIN_DISTINCT_INSTANCES = 8;

/** Fewer than RECAP_MIN_DISTINCT_INSTANCES distinct questions (regenerated by the test). */
export const RECAP_REPEATING_TEMPLATE_IDS = Object.freeze([
  'mm_A_12A_v2_mapping-nonfunction',
]);

/**
 * Distinct questions, repeating mathematics. The A2.2A logarithm template's
 * 24 distinct draws are mostly the claimant's name: its points have 8
 * versions, and the base-10 and natural-log variants have one each.
 */
export const RECAP_SAME_MATHEMATICS_TEMPLATE_IDS = Object.freeze([
  'mm_A2_2A_v2_logarithmic-graph-attributes',
]);

export const RECAP_WITHHELD_TEMPLATE_IDS = Object.freeze([
  ...RECAP_REPEATING_TEMPLATE_IDS,
  ...RECAP_SAME_MATHEMATICS_TEMPLATE_IDS,
].sort());

/*
 * WIDENED TEMPLATES, BY THE VERSION THAT WIDENED THEM (coordinator review of
 * #464, m1). The new content reaches students only when a root admin
 * publishes the course Path release; the functions that read this list may be
 * deployed before that. Until then the bank still serves the old, repeating
 * draws of these templates. Their familyVersion was raised with the
 * widening, so withholding follows the content actually served: an item drawn
 * from an older version (or with no version) is withheld as before.
 */
export const RECAP_WIDENED_TEMPLATE_VERSIONS = Object.freeze({
  'mm_A2_2A_v2_exponential-graph-attributes': 4,
  'mm_A2_2A_v2_logarithmic-graph-attributes': 4,
  'mm_A2_2A_v2_reciprocal-graph-attributes': 4,
  'mm_A2_2A_v2_root-family-graph': 4,
  'mm_A2_2A_v2_symmetry-family-graph': 4,
  'mm_A2_2C_v2_exponential-log-features': 4,
  'mm_A2_3B_v2_matrix-technology-rref': 4,
  'mm_A2_4E_v2_quadratic-context-interpolation': 4,
  'mm_A2_4E_v2_quadratic-regression-table': 4,
  'mm_A2_4E_v2_square-root-context-interpolation': 4,
  'mm_A2_5B_v2_logarithmic-ratio-scale-model': 4,
  'mm_A2_8B_v2_exponential-regression-decay-noisy': 4,
  'mm_A2_8B_v2_exponential-regression-growth-noisy': 4,
  'mm_A2_8B_v2_linear-regression-noisy': 4,
  'mm_A2_8B_v2_quadratic-regression-noisy': 4,
  'mm_A2_8C_v2_prediction-model-variants': 4,
  'mm_A_12D_v2_geometric-decay-terms-to-formula': 4,
  'mm_A_12E_v2_solve-area-height': 4,
  'mm_A_2A_v2_discrete-mapping-domain-range': 4,
  'mm_A_3G_v2_error-read-intersection': 4,
  'mm_A_3G_v2_graph-then-verify': 4,
  'mm_A_3G_v2_pricing-estimate': 4,
  'mm_A_3G_v2_savings-estimate': 4,
  'mm_A_3G_v2_transport-estimate': 4,
  'mm_A_9B_v2_growth-factor': 4,
  'mm_A_9D_v2_context-decay-graph': 4,
});

const WITHHELD = new Set(RECAP_WITHHELD_TEMPLATE_IDS);

/**
 * True when a template's recap entries must not carry its answer or solution.
 * `familyVersion` is the served item's template version.
 */
export const recapWithholdsAnswer = (templateId, familyVersion = null) => {
  const id = String(templateId ?? '').trim();
  if (WITHHELD.has(id)) return true;
  const widenedAt = RECAP_WIDENED_TEMPLATE_VERSIONS[id];
  if (widenedAt === undefined) return false;
  const served = Number(familyVersion);
  return !(Number.isFinite(served) && served >= widenedAt);
};
