/*
 * QUESTIONS WHOSE RECAP KEEPS ITS ANSWER TO ITSELF.
 *
 * A recap entry shows the correct answer and the worked solution, and it
 * stays. Most bank templates generate 13 or more distinct questions in 30
 * draws, so last week's answer is no key to this week's question. These
 * generate fewer than 8: the same question comes back, a retention re-check
 * included, and a stored answer would be its key. Their recap entries keep the
 * question and the student's own answer and leave out the correct answer and
 * the solution (pathSessionRecap.mjs).
 *
 * tests/platform/pathRecapWithheld.test.mjs regenerates this list from
 * seed/pathQuestionBank (30 seeded draws per template, compared by content)
 * and fails when it drifts. Student push J widened 26 of D's 27. The one left,
 * mm_A_12A_v2_mapping-nonfunction, has the same answer ("not a function") on
 * every draw, so however its wording varied, a recap would be the key.
 *
 * A second, named list holds templates whose draws differ in wording more
 * than in mathematics: they reach 8 distinct questions, but their answers
 * repeat as often as a repeating template's would. Their recap withholds too.
 */

export const RECAP_INSTANCE_DRAWS = 30;
export const RECAP_MIN_DISTINCT_INSTANCES = 8;

/** Fewer than RECAP_MIN_DISTINCT_INSTANCES distinct questions (regenerated by the test). */
export const RECAP_REPEATING_TEMPLATE_IDS = Object.freeze([
  'mm_A_12A_v2_mapping-nonfunction',
]);

/**
 * Distinct questions, repeating mathematics. The A2.2A logarithm template's
 * 24 distinct draws are mostly the claimant's name: its points have 8
 * versions, and the base-10 and natural-log variants have one each.
 */
export const RECAP_SAME_MATHEMATICS_TEMPLATE_IDS = Object.freeze([
  'mm_A2_2A_v2_logarithmic-graph-attributes',
]);

export const RECAP_WITHHELD_TEMPLATE_IDS = Object.freeze([
  ...RECAP_REPEATING_TEMPLATE_IDS,
  ...RECAP_SAME_MATHEMATICS_TEMPLATE_IDS,
].sort());

const WITHHELD = new Set(RECAP_WITHHELD_TEMPLATE_IDS);

/** True when a template's recap entries must not carry its answer or solution. */
export const recapWithholdsAnswer = (templateId) => WITHHELD.has(String(templateId ?? '').trim());
